### ISSUE TITLE
Misalignment when resizing in predictions panel

### ISSUE THREAD

**Issue by JarrettTo** [JarrettTo/SBAI.com-Frontend#30]
![image](https://github.com/JarrettTo/SBAI.com-Frontend/assets/104493864/7a554e9c-c566-439b-9aea-01f838918b0c)
the set of buttons (boxscore, odds, prediction) is not horizontally aligned
The ml and uo predictions arent either

**Comment by GithubSim13** [comment]
boxscore not opening so can't fix alignment, otherwise fixed
